repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: detect-private-key

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      args:
      - --line-length=79

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.0
  hooks:
  - id: isort
    args:
    - --profile=black
    - --line-length=79

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
    -   id: mypy
