on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.9"

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3

      - name: Run flake8
        run: |
          flake8 .

      - name: Run mypy
        run: |
          mypy .

      - name: Run isort
        run: |
          isort . --profile=black --line-length=79
